### PR TITLE
Add support for detecting Linux ARM64 in CMakeLists.txt

### LINKED ISSUE #67: Build for aarch64-linux
I'm keenly interested in having a working `aarch64-linux` build for IQ-Tree. It looks like there has been work done to getting it to work on the new M1 Macs ([#42](https://github.com/iqtree/iqtree2/issues/42)) If someone could point me in the right direction to get started I'd be happy to take a stab at this myself.

Cheers,
Ron

### PR DESCRIPTION
**Pull request by martin-g**
Fixes #67 

Add CI based on Github Actions that builds iqtree2 on Linux x86_64 and aarch64

### CODE REVIEW

**Comment by martin-g** [comment]
I had to replace Github Actions with CircleCI for the Linux ARM64 build because Github Actions does not support natively Linux ARM64 yet (it will soon - https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/) and it uses QEMU to emulate it. Unfortunately  the emulation is too slow and the workflow times out.
For Linux ARM64 now I use CircleCI that provides Linux ARM64 VMs for free - https://app.circleci.com/pipelines/github/martin-g/iqtree2?branch=add-support-for-linux-aarch64.

**Comment by martin-g** [comment]
https://github.com/bioconda/bioconda-recipes/pull/46434 depends on this.

**Comment by thomaskf** [comment]
Thanks, Martin, for the input on updating the codes to support Linux ARM64.

**Comment by thomaskf** [comment]
@martin-g We have just made a new release. Thanks again. Cheers.

**Pull request merged**
