### PR TITLE
Expand CI System to Build for Mac x86-64 and Windows x86-64

### PR DESCRIPTION
**Pull request by IntegerLimit**
This PR expands on the base CI System implemented in https://github.com/iqtree/iqtree2/pull/148, https://github.com/iqtree/iqtree2/pull/174, and https://github.com/iqtree/iqtree2/pull/175. This PR adds the compilation and architecture test for both Windows x86-64 and Mac x86-64. As Github Actions has not yet added support for Windows ARM, that is not included in this PR. The file has also been renamed to a more descriptive name (`build.yaml` vs `ci.yaml`) 

This serves two functions:
1. As a rough guide for other users compiling on those systems
2. As a stepping stone for more robust CI/CD in the future, incorporating builds for all architectures, and those compiled files being uploaded as Action Artefacts, or as Release Binaries.

I have also made the CI System cancel if a second commit is pushed before the task finishes, which is especially important here given the long compile time of Linux ARM (~46 Minutes).

### CODE REVIEW

**Comment by iqtree** [comment]
The patch looks very good, thanks! However, can you rename the file back to ci.yaml? (I think that is the standard for continuous integration thing).

**Comment by bqminh** [comment]
Build for Windows failed... pls have a look

**Comment by IntegerLimit** [comment]
Yep, Taking a Look Now.

**Comment by IntegerLimit** [comment]
> Build for Windows failed... pls have a look

Fixed in above commit :+1:

**Pull request merged**
