### PR TITLE
now using name decenttree.cpp

### PR DESCRIPTION
**Pull request by NicolaDM**

### CODE REVIEW

**Comment by bqminh** [comment]
@NicolaDM There are conflicts in modelunrest.cpp and .h. Please have a look above. Do you remember what you changed? (so it helps to review the merge).

**Comment by NicolaDM** [comment]
Sorry Minh, I don't remember much about this.

Looking at my commits it looks like I added a function writeInfo() to both .cpp and .h files, and I modified 
ModelUnrest::ModelUnrest() in the .cpp file to allow the reading input UNREST rates.

**Comment by bqminh** [comment]
@trongnhanuit  Am I right that you change ModelUnrest to read the parameters? It looks like both you and Nicola changed this part of the class, causing conflicts...

**Comment by trongnhanuit** [comment]
Hi Minh,
Yes, I added some code to read the model parameters for Unrest.

**Review by bqminh — APPROVED** [review]

**Pull request merged**
